<?php
namespace app\main;

use designetecnologia\main\Router;
use designetecnologia\main\inception\Controller;
use designetecnologia\main\exception\UndefinedActionException;

//The template will be generated by models/Layout object
use app\main\models\Layout;

/**
 * Describes App main controller for handling requests
 *
 * For PHP versions 5.4+
 *
 * @category   Framework
 * @author     Elionai Moura <eli.embits@gmail.com>
 * @copyright  2015 Design e Tecnologia by Elionai Moura <http://designetecnologia.com.br>
 * @license    The MIT license <https://opensource.org/licenses/MIT>
 * @version    0.1
 * @link       https://github.com/elionaimc/letbit-for-php
 *
 */
class App extends Controller
{
  /**
   * Overloads the lib/main/inception/Controller::__call function
   * @see /designetecnologia/main/inception/Controller::__call()
   */
  public function __call($action, $vars)
  {
    /**
     * Implements the abstract Controller::index() function
     */
    if (!is_callable($action)) $this->index(); // if called action do not exists, calls index()
  }

  /**
   * Implements the abstract Controller::index() function
   */
  public function index()
  {
    $router = Router::getInstance();
    $params = $router->getParams();
    $l = new Layout();
    $result = $l->render(dirname(__FILE__).DS.'views/main.php');
    $router->setBody($result);
  }

  public function notFound($msg = null)
  {
    parent::notFound("Action failed. Performing App::index() action");
  }
}
